from crt_tree_automation import _nb_data_import
from pprint import pprint


def _build_directories(nb_data):
    """
    This function checks for and builds site directories as needed in the tree.
    """

    # TODO #6

    return ()


def _generate_session():
    """
    This function generates a templated session config
    """

    # TODO #7
    print("testing")
    return ()


def _session_generator():
    """
    Main function that kicks off the session generation pipeline.

    Requires nb_data input generated by ./nb_data_import.py.
    """

    nb_data = _nb_data_import._nb_data_import()

    # _build_directories(nb_data)

    return ()
